---
- name: Install and configure Node Exporter
  hosts: all
  become: yes
  tasks:

    - name: Download Node Exporter archive
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Node Exporter archive
      unarchive:
        src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move node_exporter binary to /usr/local/bin
      copy:
        src: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Remove extracted Node Exporter files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/node_exporter-1.5.0.linux-amd64
        - /tmp/node_exporter-1.5.0.linux-amd64.tar.gz

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /bin/false
        system: yes
        create_home: no

    - name: Create systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

